description: Test configuration

providers:
  - id: openai:gpt-4
    config:
      apiKey: sk-proj-vM0ob8TYljv25QejYlJDT3BlbkFJRld6O7nCrsudt0vS8LTW

prompts:
  - file://prompt_v1.md

tests:
  - description: Test case 1
    vars:
      questions: "How does Docker containerization improve application deployment?"
      context: "Modern software development emphasizes scalability, performance, and maintainability in cloud-native environments."
      categories: "technical"

outputPath: ./test_results.json
